### ISSUE TITLE
EnableExperimentalTeleport: TeleportationManager throws console error when dog owner is done sleeping

### ISSUE THREAD

**Issue by Mikkel136** [HeroGamers/MyDog#52]
**What happened?**
After "EnableExperimentalTeleport" was enabled, a console error is being thrown after a dog's owner finished sleeping. Dog was upright, roaming the area. Nothing gameplay-wise was seemingly affected.

**Details**
Console dump: _[https://pastebin.com/VQGtTVZR](url)_
Config file: _[https://pastebin.com/9DCFMDn7](url)_

**Environment**
Server: _git-Purpur-1747 (MC: 1.19.1)_
MyDog: _MyDog v0.1.3_

**Steps to re-create this issue**
1) Enable "EnableExperimentalTeleport" in config.yml
2) Tame a dog, make sure it's not sitting
3) Set the time to night, place a bed and go to sleep
4) Console error has been thrown in the server log

**Comment by HeroGamers** [comment]
Thanks for the bug report!

The Experimental Teleport is indeed VERY experimental, and last time I checked, it was extremely unstable, and I couldn't really get it to work correctly.. (though your bug doesn't seem to be regarding that, so I'll be taking a look at it eventually).

For now, I would recommend against using the Experimental Teleport, since the feature to enable it was more for development purposes ^^

I'd be pleased to hear any feedback regarding it though! It's been a long time since I last tried to make it work, and it didn't really work in my favor lol

Cheers,
- Hero
