### ISSUE TITLE
Error in Console when interacting with dogs

### ISSUE THREAD

**Issue by Darkmager** [HeroGamers/MyDog#60]
hello i am using mc pets and modelengine with mythic mobs so whenever someone uses /dogs this error spams in console
https://pastebin.com/Q6iAF57c

**Comment by Darkmager** [comment]
also now in some pets/model it is now showing dogs instead of the original models now

**Comment by HeroGamers** [comment]
I don't think the model thing has anything to do with MyDog, but the error seems to be caused by the level missing when creating a dog.
This was not caused by running `/dogs`, but by interacting with a dog. Can you also attach the error from typing `/dogs`?

Do you have levels enabled, and what is the level configuration? I might just have forgotten to initialize the level before fetching it.

**Comment by Darkmager** [comment]
there is no error from console when  do /dogs , here is the level files 
https://pastebin.com/ytR7SdsT

**Comment by HeroGamers** [comment]
Issue reported another time on SpigotMC: https://www.spigotmc.org/threads/mydog.389581/page-4#post-4504231
